(require :conf.core.which-key)
(require :conf.core.lsp)
(require :conf.core.treesitter)
(require :conf.core.telescope)
(require :conf.core.cmp)
(require :conf.core.gitsigns)
(require :conf.core.comment)
(require :conf.core.project)
(require :conf.core.gps)
(require :conf.core.zk)
(require :conf.core.formatter)

