(require :conf.core.which-key)
(require :conf.core.orgmode)
(require :conf.core.lsp)
(require :conf.core.treesitter)
(require :conf.core.telescope)
(require :conf.core.luasnip)
(require :conf.core.cmp)
(require :conf.core.gitsigns)
(require :conf.core.comment)
(require :conf.core.project)
(require :conf.core.zk)
(require :conf.core.formatter)
(require :conf.core.leap)

