name: "Build for cachix"
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cachix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
    - uses: cachix/install-nix-action@68043fd3c39467300b2cf963b245dcea7ea979d6
    - uses: cachix/cachix-action@490a246fbc7f92208d309eeb54383a4d828cedc1
      with:
        name: arnarg
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build all packages with most recent nixos-unstable
      run: |
        nix-build --arg pkgs 'import (fetchTarball https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz) {}' --no-out-link packages/default.nix
